
server:
  port: 8000

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/cuxaud?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
    password: wxb123456
    driver: com.mysql.jdbc.Driver

    hikari:
      pool-name: user-1
      minimum-idle: 30
      maximum-pool-size: 30
      connectionTimeout: 60000
      idleTimeout: 60000
      validationTimeout: 3000
      maxLifetime: 60000
      register-mbeans: true

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  config-location: classpath:/mybatis-config.xml
  type-aliases-package: com.example.demo.entity

http:
  maxTotal: 500
  defaultMaxPerRoute: 300
  #设置连接超时时间，单位毫秒
  connectTimeout: 10000
  #http clilent中从connetcion pool中获得一个connection的超时时间,单位毫秒
  connectionRequestTimeout: 500
  #请求获取数据的超时时间，单位毫秒。 如果访问一个接口，多少时间内无法返回数据，就直接放弃此次调用
  socketTimeout: 15000
  staleConnectionCheckEnabled: true
